version = 0.1
[dev]
[dev.deploy]
[dev.deploy.parameters]
stack_name = "media"
s3_bucket = "583168578067-sam"
s3_prefix = "media"
region = "ca-central-1"
profile = "personal"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = """
    Env=\"dev\"
"""
tags = """
    application=\"media\"
    AppManagerCFNStackKey=\"media\"
"""
